In [2]:
import numpy as np
np.set_printoptions(precision=4)

In [3]:
def proj(x, y): # Proj of X on Y
    return np.dot(x.T, y)*y

In [4]:
def mag(x):
    return np.linalg.norm(x)

In [5]:
def GS_orthogonalization(A): # Rows are a1, a2 ... ai
    temp = np.zeros((A.shape[1]), dtype=float)
    for i in range(len(A)):
        temp = A[i]
        for j in range(i):
            A[i] -= proj(temp, A[j])
        A[i] /= mag(A[i])
    return A

Cleaning for values less than threshold becaus some values are very close to 0 like 1e-20 in the result which should be 0

In [6]:
def clean(A, threshold = 1e-10):
    mask = np.where(abs(A)<threshold, 0, A)
    return mask

Code for testing orthogonality

In [17]:
def orth_test(A, threshold = 1e-10):
    orthogonal = True
    for i in range(len(A)):
        for j in range(i+1,len(A)):
            mult = np.dot(A[i], A[j].T)
            if mult > threshold:
                orthogonal = False
    return orthogonal

In [22]:
A = np.array([[1, -1, 1], [1, 0,1], [1,1,2]], dtype=float) # HW Problem
res = clean(GS_orthogonalization(A))
print(res)
print("Orthogonality Test (True if orthogonal): ", orth_test(res))

[[ 0.5774 -0.5774  0.5774]
 [ 0.4082  0.8165  0.4082]
 [-0.7071  0.      0.7071]]
Orthogonality Test (True if orthogonal):  True


Test with random matrices

In [24]:
test_matrix = np.random.rand(5,5)
test_res = clean(GS_orthogonalization(test_matrix))
print(test_res)
print("Orthogonality Test (True if orthogonal): ", orth_test(test_res))


[[ 0.5822  0.5237  0.3657  0.0584  0.4996]
 [-0.3962  0.4721 -0.2722  0.7346  0.0801]
 [-0.3545  0.0655  0.8718  0.1233 -0.308 ]
 [ 0.4485  0.3594 -0.1361  0.0483 -0.8055]
 [ 0.421  -0.6077  0.1172  0.6629 -0.0169]]
Orthogonality Test (True if orthogonal):  True
