In [36]:
import numpy as np
np.set_printoptions(precision=4)

In [28]:
def proj(x, y): # Proj of X on Y
    return np.dot(x.T, y)*y

In [29]:
def mag(x):
    return np.linalg.norm(x)

In [30]:
def GS_orthogonalization(A): # Rows are a1, a2 ... ai
    temp = np.zeros((A.shape[1]), dtype=float)
    for i in range(len(A)):
        temp = A[i]
        for j in range(i):
            A[i] -= proj(temp, A[j])
        A[i] /= mag(A[i])
    return A

In [56]:
def clean(A, threshold = 1e-10):
    mask = np.where(abs(A)<threshold, 0, A)
    return mask
        

In [59]:
A = np.array([[1, -1, 1], [1, 0,1], [1,1,2]], dtype=float)
res = clean(GS_orthogonalization(A))
print(res)

[[ 0.5774 -0.5774  0.5774]
 [ 0.4082  0.8165  0.4082]
 [-0.7071  0.      0.7071]]
